---
name: "Publish Docker image"

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: mback2k/action-docker-package@master
        with:
          registry_password: ${{ secrets.GITHUB_TOKEN }}
...
